import React from "react";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Head from "next/head";
import { Button } from "@chakra-ui/react";
import HomeCompIndex from "../components/home/ui/index";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sean's Project</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* <NavBar /> */}

      <main>
        <HomeCompIndex />
      </main>
    </div>
  );
}
